app/calls/forms.py
from flask_wtf import FlaskForm
from wtforms import validators
from wtforms.fields import StringField
from wtforms.widgets import TextArea


class CommentForm(FlaskForm):
    comment = StringField(u'Comment', validators=[validators.input_required(),
                          validators.Length(min=10, max=250)],
                          widget=TextArea())

app/calls/__init__.py
from flask import Blueprint


calls_bp = Blueprint('calls_bp', __name__)
from . import views

app/calls/views.py
import datetime
from flask import render_template, request
from flask import current_app as app
from flask_login import login_required
from ..models import db, Calls, CallsComments
from . import calls_bp
from .forms import CommentForm



@calls_bp.route('/', methods=['GET'])
@calls_bp.route('/calls/', methods=['GET'])
@calls_bp.route('/calls/<int:page>', methods=['GET'])
def index(page=1):
    calls = Calls.query.filter_by(is_called_back = False).order_by("calltime DESC").paginate(page,app.config['ITEMS_PER_PAGE'])
    return render_template('calls/index.html', calls=calls)


@calls_bp.route('/calls/call/<int:call_id>', methods=['GET', 'POST'])
@login_required
def call_detail(call_id):
    call = Calls.query.get(call_id)
    if request.method == 'POST':
        if (request.form.get('comment')):
            add_comment(call.id)
        if (request.form.get('called_back')):
            set_called_back(call.id)

    call_comments = CallsComments.query.filter_by(call_id=call_id).order_by("comment_date DESC")
    form = CommentForm()
    return render_template('calls/detail.html', call=call, form=form,
                           call_comments=call_comments)


def add_comment(id):
    comment = CallsComments()
    comment.text = request.form['comment']
    comment.call_id = id
    comment.user_id = 1
    comment.comment_date = datetime.datetime.now()

    db.session.add(comment)
    db.session.commit()


def set_called_back(id):
    call = Calls.query.get(id)
    call.is_called_back = 1
    db.session.commit()

app/templates/calls/comment_form.html
<form method="POST">
  {{ form.comment(cols="80", rows="5") }}
  <input type="submit" value="Комментировать">
</form>

app/templates/calls/comment_list.html
{% if call_comments %}
<ul>
  {% for call_comment in call_comments %}
  <li>
    <strong>{{ call_comment.comment_date.strftime('%d.%m.%y %H:%M') }} - {{ call_comment.user.username }}</strong><br />
      {{ call_comment.text}}
  </li>
  {% endfor %}
</ul>
{% else %}
<p>Нет комментариев</p>
{% endif %}

app/templates/calls/detail.html
{% extends 'base.html' %}
{% block title %}
  Вход в систему
{% endblock %}
{% block userinfo %}

{% endblock %}
{% block content %}
<div>
<a href="{{url_for('calls_bp.index') }}"> << Назад</a></div>
<table>
  <tbody>
    <tr>
      <td>Откуда звонили
      </td>
      <td>{{ call.caller_id }}
      </td>
    </tr>
    <tr>
      <td>На какой номер звонили
      </td>
      <td>{{ call.called_id }}
      </td>
    </tr>
    <tr>
      <td>Время звонка
      </td>
      <td>{{ call.calltime.strftime('%d.%m.%y %H:%M') }}
      </td>
    </tr>
    <tr>
      <td>Перезвонили?
      </td>
      <td><form method="POST">{% if call.is_called_back == true %}
        <input type="checkbox" checked disabled />
        {% else %}
        <input type="checkbox" name="called_back" /> <input type="submit" value="Перезвонить" />
        {% endif %}
        </form>
      </td>
    </tr>
  </tbody>
</table>
<div id="comment-form">
  {% include 'calls/comment_form.html' %}
</div>
<div id="comments">
  {% include 'calls/comment_list.html' %}
</div>
{% endblock %}

app/templates/calls/index.html
{% extends 'base.html' %}
{% from 'pagination.html' import render_pagination with context %}
{% block title %}
  Пропущенные звонки
{% endblock %}
{% block content %}
    {{ render_pagination(calls, "calls_bp.index") }}
    <table class="table table-hover table-sm">
      <thead class="thead-dark">
        <tr>
          <th>
            Номер телефона
          </th>
          <th>
            На какой номер звонили
          </th>
          <th>
            Дата и время
          </th>
        </tr>
      </thead>
      <tbody>
        {% if calls %}
        {% for call in calls.items %}
        <tr scope="row">
          <td>
            <a href="{{ url_for('calls_bp.call_detail', call_id=call.id) }}">{{ call.caller_id }}</a>
          </td>
          <td>
            {{ call.called_id }}
          </td>
          <td>
            {{ call.calltime.strftime('%d.%m.%y %H:%M') }}
          </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
          <td colspan="3">
            Нет данных о пропущенных
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
{{ render_pagination(calls, "calls_bp.index") }}
{% endblock %}